src/Entity/Vehicule.php
<?php

namespace App\Entity;

use App\Repository\VehiculeRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VehiculeRepository::class)
 */
class Vehicule
{
     /**
     * @var string
     *
     * @ORM\Column(name="id", type="string")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class="Doctrine\Bundle\DoctrineBundle\IdGenerator")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $country_of_registration;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $numberplate;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $brand;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $model;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $color;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $year;

    /**
     * @ORM\Column(type="string", length=255, nullable=true, options={"default":"default-vehicule.jpg"})
     */
    private $vehicule_picture;

    /**
     * @ORM\ManyToOne(targetEntity=TypeOfVehicule::class)
     */
    private $typeOfVehicule;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?string $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getCountryOfRegistration(): ?string
    {
        return $this->country_of_registration;
    }

    public function setCountryOfRegistration(?string $country_of_registration): self
    {
        $this->country_of_registration = $country_of_registration;

        return $this;
    }

    public function getNumberplate(): ?string
    {
        return $this->numberplate;
    }

    public function setNumberplate(?string $numberplate): self
    {
        $this->numberplate = $numberplate;

        return $this;
    }

    public function getBrand(): ?string
    {
        return $this->brand;
    }

    public function setBrand(?string $brand): self
    {
        $this->brand = $brand;

        return $this;
    }

    public function getModel(): ?string
    {
        return $this->model;
    }

    public function setModel(?string $model): self
    {
        $this->model = $model;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(?string $color): self
    {
        $this->color = $color;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(?int $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getVehiculePicture(): ?string
    {
        return $this->vehicule_picture;
    }

    public function setVehiculePicture(?string $vehicule_picture): self
    {
        $this->vehicule_picture = $vehicule_picture;

        return $this;
    }

    public function getTypeOfVehicule(): ?TypeOfVehicule
    {
        return $this->typeOfVehicule;
    }

    public function setTypeOfVehicule(?TypeOfVehicule $typeOfVehicule): self
    {
        $this->typeOfVehicule = $typeOfVehicule;

        return $this;
    }
}

src/Form/VehiculeType.php
<?php

namespace App\Form;

use App\Entity\TypeOfVehicule;
use App\Entity\Vehicule;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class VehiculeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('country_of_registration')
            ->add('numberplate', TextType::class, [
                'required' => false, 
                'attr' => [ 
                        'class'=> 'custom-field-form', 
                        'pattern' => '[-0-9A-Z]{9}',
                        'maxlength' => '9'
                ]
            ])
            ->add('brand')
            ->add('model')
            ->add('color', ChoiceType::class, [
                'choices'  => [
                    'Blanche' => 'Blanche',
                    'Noir' => 'Noir',
                    'Rouge' => 'Rouge',
                    'Verte' => 'Verte',
                    'Jaune' => 'Jaune',
                    'Orange' => 'Orange',
                    'Bleu' => 'Bleu',
                    'Bleu Marine' => 'Bleu Marine',
                    'Grise' => 'Grise',
                    'Violette' => 'Violette',
                    'Rose' => 'Rose',
                    'Autre' => 'Autre',
                ],
            ])
            ->add('year')
            ->add('vehicule_picture',FileType::class, [
                'label' => 'profil picture',
                'attr' => [ 'class'=> 'custom-field-form'],

                // unmapped means that this field is not associated to any entity property
                'mapped' => false,

                // make it optional so you don't have to re-upload the PDF file
                // every time you edit the Product details
                'required' => false,
                // unmapped fields can't define their validation using annotations
                // in the associated entity, so you can use the PHP constraint classes
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypesMessage' => 'Please upload a valid picture document',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/jpg',
                            'image/pgn',
                            'image/gif'
                        ],
                    ])
                ],
            ])
            ->add('typeOfVehicule', EntityType::class, [
            'class' => TypeOfVehicule::class,
            'query_builder' => function (EntityRepository $er) {
                return $er->createQueryBuilder('u')
                    ->orderBy('u.type', 'ASC');
            },
            'choice_label' => 'type',
        ]) 
    
        
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Vehicule::class,
        ]);
    }
}

src/Controller/VehiculeController.php
<?php

namespace App\Controller;

use App\Entity\Vehicule;
use App\Form\VehiculeType;
use App\Repository\VehiculeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/vehicule")
 */
class VehiculeController extends AbstractController
{
    /**
     * @Route("/", name="vehicule_index", methods={"GET"})
     */
    public function index(VehiculeRepository $vehiculeRepository): Response
    {
        return $this->render('vehicule/index.html.twig', [
            'vehicules' => $vehiculeRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="vehicule_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $vehicule = new Vehicule();
        $form = $this->createForm(VehiculeType::class, $vehicule);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($vehicule);
            $entityManager->flush();

            return $this->redirectToRoute('vehicule_index');
        }

        return $this->render('vehicule/new.html.twig', [
            'vehicule' => $vehicule,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="vehicule_show", methods={"GET"})
     */
    public function show(Vehicule $vehicule): Response
    {
        return $this->render('vehicule/show.html.twig', [
            'vehicule' => $vehicule,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="vehicule_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Vehicule $vehicule): Response
    {
        $form = $this->createForm(VehiculeType::class, $vehicule);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('vehicule_index');
        }

        return $this->render('vehicule/edit.html.twig', [
            'vehicule' => $vehicule,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="vehicule_delete", methods={"POST"})
     */
    public function delete(Request $request, Vehicule $vehicule): Response
    {
        if ($this->isCsrfTokenValid('delete'.$vehicule->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($vehicule);
            $entityManager->flush();
        }

        return $this->redirectToRoute('vehicule_index');
    }
}

templates/vehicule/_delete_form.html.twig
<form method="post" action="{{ path('vehicule_delete', {'id': vehicule.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ vehicule.id) }}">
    <button class="btn">Delete</button>
</form>

templates/vehicule/_form.html.twig
 <section class="section-padding">
    <div class="row justify-content-center ">
        <div class="col-10 form-info">
        <p class=""><i style="color: #F99C25;padding:5px;"class="fas fa-circle"></i>Informations de votre véhicule :</p>
            {{ form_start(vehicule) }}
                    <div class="custom-input-div">
                        {{ form_label(vehicule.country_of_registration, 'Pays d\'immatriculation') }}
                        {{ form_widget(vehicule.country_of_registration, {'attr': {'class': 'custom-field-form','placeholder': ' Pays'}}) }}
                    </div> 
                    <div class='red-text'>{{ form_errors(vehicule.country_of_registration)}}</div>
                    <div class="custom-input-div">
                        {{ form_label(vehicule.numberplate, 'Plaque d\'immatriculation') }}
                        {{ form_widget(vehicule.numberplate, {'attr': {'class': 'custom-field-form','placeholder': 'XX-123-XX'}}) }}
                    </div>
                    <div class='red-text'>{{ form_errors(vehicule.numberplate)}}</div>
                    <div class="custom-input-div">
                        {{ form_label(vehicule.brand,'Marque') }} 
                        {{ form_widget(vehicule.brand, {'attr': {'class': 'custom-field-form','placeholder': ' Exemple : Opel'}}) }}
                    </div> 
                    <div class='red-text'>{{ form_errors(vehicule.brand)}}</div>
                        <div class="custom-input-div">
                        {{ form_label(vehicule.model,'Modèle') }} 
                        {{ form_widget(vehicule.model, {'attr': {'class': 'custom-field-form','placeholder': ' Exemple : Corsa'}}) }}
                    </div> 
                    <div class='red-text'>{{ form_errors(vehicule.model)}}</div>
                        <div class="custom-input-div">
                        {{ form_label(vehicule.color,'Couleur') }} 
                        {{ form_widget(vehicule.color, {'attr': {'class': 'custom-field-form','placeholder': ' Sélectionnée une couleur'}}) }}
                    </div> 
                    <div class='red-text'>{{ form_errors(vehicule.color)}}</div>
                    <div class="custom-input-div">
                        {{ form_label(vehicule.year,'Année') }} 
                        {{ form_widget(vehicule.year, {'attr': {'class': 'custom-field-form','placeholder': ' Année'}}) }}
                    </div> 
                    <div class='red-text'>{{ form_errors(vehicule.year)}}</div>
                        <div class="custom-input-div">
                        <div class="input-field">
                            {{ form_label(vehicule.typeOfVehicule, 'Type de véhicule') }}
                            {{ form_widget(vehicule.typeOfVehicule, {'attr': {'class': 'custom-field-form'}}) }}
                        </div>
                        <div class='red-text'>{{ form_errors(vehicule.typeOfVehicule)}}</div>
                    </div>
                        <div class='red-text'>{{ form_errors(vehicule.vehicule_picture)}}</div>
                            <div class="custom-file fileUpload" id='btnHeigt'>
                                {{ form_widget(vehicule.vehicule_picture, { 'attr': {
                                    'accept' : '.pdf,.jpg,.doc,.docx,.png,.gif',
                                    'size' : '20000000', 
                                    'type' : 'file',
                                    'class': 'custom-field-form upload'
                                    }}) 
                                }}
                                <span>Ajouter une photo de mon véhicule</span>
                            </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 mb-4 mt-4 d-flex justify-content-center">
                    <button  type='submit' class="col-md-10 button-update-profile">Sauvegarder mon véhicule</button>
                </div>
            {{ form_end(vehicule) }}
        </div>
    </div>

</section> 

templates/vehicule/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Vehicule{% endblock %}

{% block body %}

    {{ include('vehicule/_form.html.twig', {'button_label': 'Update'}) }}


    {{ include('vehicule/_delete_form.html.twig') }}
{% endblock %}

templates/vehicule/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vehicule index{% endblock %}

{% block body %}
    <h1>Vehicule index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Country_of_registration</th>
                <th>Numberplate</th>
                <th>Brand</th>
                <th>Model</th>
                <th>Color</th>
                <th>Year</th>
                <th>Vehicule_picture</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for vehicule in vehicules %}
            <tr>
                <td>{{ vehicule.id }}</td>
                <td>{{ vehicule.countryOfRegistration }}</td>
                <td>{{ vehicule.numberplate }}</td>
                <td>{{ vehicule.brand }}</td>
                <td>{{ vehicule.model }}</td>
                <td>{{ vehicule.color }}</td>
                <td>{{ vehicule.year }}</td>
                <td>{{ vehicule.vehiculePicture }}</td>
                <td>
                    <a href="{{ path('vehicule_show', {'id': vehicule.id}) }}">show</a>
                    <a href="{{ path('vehicule_edit', {'id': vehicule.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('vehicule_new') }}">Create new</a>
{% endblock %}

templates/vehicule/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Vehicule{% endblock %}

{% block body %}
    <h1>Create new Vehicule</h1>

    {{ include('vehicule/_form.html.twig') }}

    <a href="{{ path('vehicule_index') }}">back to list</a>
{% endblock %}

templates/vehicule/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vehicule{% endblock %}

{% block body %}
    <h1>Vehicule</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ vehicule.id }}</td>
            </tr>
            <tr>
                <th>Country_of_registration</th>
                <td>{{ vehicule.countryOfRegistration }}</td>
            </tr>
            <tr>
                <th>Numberplate</th>
                <td>{{ vehicule.numberplate }}</td>
            </tr>
            <tr>
                <th>Brand</th>
                <td>{{ vehicule.brand }}</td>
            </tr>
            <tr>
                <th>Model</th>
                <td>{{ vehicule.model }}</td>
            </tr>
            <tr>
                <th>Color</th>
                <td>{{ vehicule.color }}</td>
            </tr>
            <tr>
                <th>Year</th>
                <td>{{ vehicule.year }}</td>
            </tr>
            <tr>
                <th>Vehicule_picture</th>
                <td>{{ vehicule.vehiculePicture }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('vehicule_index') }}">back to list</a>

    <a href="{{ path('vehicule_edit', {'id': vehicule.id}) }}">edit</a>

    {{ include('vehicule/_delete_form.html.twig') }}
{% endblock %}