src/Entity/Trip.php
<?php

namespace App\Entity;

use App\Repository\TripRepository;
use Doctrine\ORM\Mapping as ORM;
use JsonSerializable;

/**
 * @ORM\Entity(repositoryClass=TripRepository::class)
 */
class Trip implements JsonSerializable
{
     /**
     * @var string
     *
     * @ORM\Column(name="id", type="string")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class="Doctrine\Bundle\DoctrineBundle\IdGenerator")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $departure;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $arrival;

    /**
     * @ORM\Column(type="date")
     */
    private $date_of_trip;

    /**
     * @ORM\Column(type="integer")
     */
    private $passengers;

    /**
     * @ORM\Column(type="boolean", options={"default" : 0})
     */
    private $trip_full;

    /**
     * @ORM\Column(type="boolean", options={"default" : 0})
     */
    private $trip_completed;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $driver;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $duration;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $distance;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $startTime;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $tripStarted;

    /**
     * @ORM\Column(type="date")
     */
    private $created_at;


    public function getId(): ?string
    {
        return $this->id;
    }

    public function getDeparture(): ?string
    {
        return $this->departure;
    }

    public function setDeparture(string $departure): self
    {
        $this->departure = $departure;

        return $this;
    }

    public function getArrival(): ?string
    {
        return $this->arrival;
    }

    public function setArrival(string $arrival): self
    {
        $this->arrival = $arrival;

        return $this;
    }

    public function getDateOfTrip(): ?\DateTimeInterface
    {
        return $this->date_of_trip;
    }

    public function setDateOfTrip(\DateTimeInterface $date_of_trip): self
    {
        $this->date_of_trip = $date_of_trip;

        return $this;
    }

    public function getPassengers(): ?int
    {
        return $this->passengers;
    }

    public function setPassengers(int $passengers): self
    {
        $this->passengers = $passengers;

        return $this;
    }

    public function getTripFull(): ?bool
    {
        return $this->trip_full;
    }

    public function setTripFull(bool $trip_full): self
    {
        $this->trip_full = $trip_full;

        return $this;
    }

    public function getTripCompleted(): ?bool
    {
        return $this->trip_completed;
    }

    public function setTripCompleted(bool $trip_completed): self
    {
        $this->trip_completed = $trip_completed;

        return $this;
    }

    public function getDriver(): ?User
    {
        return $this->driver;
    }

    public function setDriver(?User $driver): self
    {
        $this->driver = $driver;

        return $this;
    }

    public function getDuration(): ?string
    {
        return $this->duration;
    }

    public function setDuration(string $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function getDistance(): ?string
    {
        return $this->distance;
    }

    public function setDistance(string $distance): self
    {
        $this->distance = $distance;

        return $this;
    }

    public function getStartTime(): ?\DateTimeInterface
    {
        return $this->startTime;
    }

    public function setStartTime(?\DateTimeInterface $startTime): self
    {
        $this->startTime = $startTime;

        return $this;
    }

    public function getTripStarted(): ?bool
    {
        return $this->tripStarted;
    }

    public function setTripStarted(?bool $tripStarted): self
    {
        $this->tripStarted = $tripStarted;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function jsonSerialize() {
        return [
            'id' => $this->getId(),
            'arrival' => $this->getArrival(),
            'departure' => $this->getDeparture(),
        ];
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use JsonSerializable;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="Cet email est déjà utilisé.")
 */
class User implements UserInterface, JsonSerializable
{
     /**
     * @var string
     *
     * @ORM\Column(name="id", type="string")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class="Doctrine\Bundle\DoctrineBundle\IdGenerator")
     */
    private $id;

     /**
     * @ORM\Column(type="string", length=180, unique=true, nullable=true) 
     * @Assert\Email(
     *     message = "L'email '{{ value }}' n'est pas valide"
     * )
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $last_name;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_of_birth;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $bio;

    /**
     * @ORM\Column(type="string", length=255, nullable=true, options={"default":"default_profile_picture.jpg"})
     */
    private $profile_picture;

    /**
     * @ORM\Column(type="date", nullable=false)
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $profile_completed;

    /**
     * @ORM\Column(type="integer")
     */
    private $trips_made;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $global_rating;

    /**
     * @ORM\ManyToOne(targetEntity=UserExperienceLevel::class)
     */
    private $user_experience;

    /**
     * @ORM\OneToOne(targetEntity=TravelPreferences::class, cascade={"persist","remove"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $travel_preferences;

    /**
     * @ORM\OneToOne(targetEntity=Vehicule::class, cascade={"persist","remove"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $vehicule;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $resetToken;

    public function getId(): ?string
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): ?self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(?string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(?string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getDateOfBirth(): ?\DateTimeInterface
    {
        return $this->date_of_birth;
    }

    public function setDateOfBirth(?\DateTimeInterface $date_of_birth): self
    {
        $this->date_of_birth = $date_of_birth;

        return $this;
    }

    public function getPhone(): ?int
    {
        return $this->phone;
    }

    public function setPhone(?int $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getBio(): ?string
    {
        return $this->bio;
    }

    public function setBio(?string $bio): self
    {
        $this->bio = $bio;

        return $this;
    }

    public function getProfile_Picture(): ?string
    {
        return $this->profile_picture;
    }

    public function setProfile_Picture(?string $profile_picture): self
    {
        $this->profile_picture = $profile_picture;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getProfileCompleted(): ?bool
    {
        return $this->profile_completed;
    }

    public function setProfileCompleted(bool $profile_completed): self
    {
        $this->profile_completed = $profile_completed;

        return $this;
    }

    public function getTripsMade(): ?int
    {
        return $this->trips_made;
    }

    public function setTripsMade(int $trips_made): self
    {
        $this->trips_made = $trips_made;

        return $this;
    }

    public function getGlobalRating(): ?float
    {
        return $this->global_rating;
    }

    public function setGlobalRating(?float $global_rating): self
    {
        $this->global_rating = $global_rating;

        return $this;
    }

    public function getUserExperience(): ?UserExperienceLevel
    {
        return $this->user_experience;
    }

    public function setUserExperience(?UserExperienceLevel $user_experience): self
    {
        $this->user_experience = $user_experience;

        return $this;
    }

    public function getTravelPreferences(): ?TravelPreferences
    {
        return $this->travel_preferences;
    }

    public function setTravelPreferences(?TravelPreferences $travel_preferences): ?self
    {
        $this->travel_preferences = $travel_preferences;

        return $this;
    }

    public function getVehicule(): ?Vehicule
    {
        return $this->vehicule;
    }

    public function setVehicule(?Vehicule $vehicule): ?self
    {
        $this->vehicule = $vehicule;

        return $this;
    }
    
    public function jsonSerialize() {
        return [
            'id' => $this->getId(),
            'firstName' => $this->getFirstName(),
            'lastName' => $this->getLastName(),
            'profile_picture' => $this->getProfile_Picture(),
        ];
    }

    public function getResetToken(): ?string
    {
        return $this->resetToken;
    }

    public function setResetToken(?string $resetToken): self
    {
        $this->resetToken = $resetToken;

        return $this;
    }

}

src/Entity/Vehicule.php
<?php

namespace App\Entity;

use App\Repository\VehiculeRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VehiculeRepository::class)
 */
class Vehicule
{
     /**
     * @var string
     *
     * @ORM\Column(name="id", type="string")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class="Doctrine\Bundle\DoctrineBundle\IdGenerator")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $country_of_registration;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $numberplate;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $brand;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $model;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $color;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $year;

    /**
     * @ORM\Column(type="string", length=255, nullable=true, options={"default":"default-vehicule.jpg"})
     */
    private $vehicule_picture;

    /**
     * @ORM\ManyToOne(targetEntity=TypeOfVehicule::class)
     */
    private $typeOfVehicule;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?string $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getCountryOfRegistration(): ?string
    {
        return $this->country_of_registration;
    }

    public function setCountryOfRegistration(?string $country_of_registration): self
    {
        $this->country_of_registration = $country_of_registration;

        return $this;
    }

    public function getNumberplate(): ?string
    {
        return $this->numberplate;
    }

    public function setNumberplate(?string $numberplate): self
    {
        $this->numberplate = $numberplate;

        return $this;
    }

    public function getBrand(): ?string
    {
        return $this->brand;
    }

    public function setBrand(?string $brand): self
    {
        $this->brand = $brand;

        return $this;
    }

    public function getModel(): ?string
    {
        return $this->model;
    }

    public function setModel(?string $model): self
    {
        $this->model = $model;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(?string $color): self
    {
        $this->color = $color;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(?int $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getVehiculePicture(): ?string
    {
        return $this->vehicule_picture;
    }

    public function setVehiculePicture(?string $vehicule_picture): self
    {
        $this->vehicule_picture = $vehicule_picture;

        return $this;
    }

    public function getTypeOfVehicule(): ?TypeOfVehicule
    {
        return $this->typeOfVehicule;
    }

    public function setTypeOfVehicule(?TypeOfVehicule $typeOfVehicule): self
    {
        $this->typeOfVehicule = $typeOfVehicule;

        return $this;
    }
}

src/Form/TripType.php
<?php

namespace App\Form;

use App\Entity\Trip;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TimeType;

class TripType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date_of_trip', DateType::class, [
                'widget' => 'single_text',
                'attr' => ['class' => 'form-control'],
            ])
            ->add('startTime', TimeType::class, [
                'input'  => 'datetime',
                'widget' => 'single_text',
                'attr' => ['class' => 'form-control'],
                'with_seconds'=>  false,
            ])
            ->add('passengers')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Trip::class,
        ]);
    }
}

templates/trip/_delete_form.html.twig
<form method="post" action="{{ path('trip_delete', {'id': trip.id}) }}" onsubmit="return confirm('Etes vous sûre de vouloir supprimer ce trajet ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ trip.id) }}">
    <button type="submit" class="btn CO">Supprimer le trajet</button>
</form>

templates/trip/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}Trip{% endblock %}

{% block body %}

        {% for message in app.flashes('success') %}
            <div class="alert alert-success text-white">
                {{ message }}
            </div>
        {% endfor %}
        {% for message in app.flashes('error') %}
            <div class="alert alert-danger text-white">
                {{ message }}
            </div>
        {% endfor %}
       <div class="container mt-5">
          <h4 class="text-center">Détails du voyage</h4>
            <div class="card-custom-detail mt-5">
              <div class="plan-detail">
              <div class="d-flex justify-content-between mb-2">
                <h3>{{trip.dateOfTrip|date("d M")}}</h3>
                {% if trip.tripFull == true and trip.tripStarted == false %}
                    <h3>Complet</h3>
                {% elseif trip.tripStarted == true and trip.tripCompleted == false %}
                    <h3> Le trajet a commencer</h3>
                {% elseif trip.tripStarted == true and trip.tripCompleted == true %}
                    <h3> Trajet terminé </h3>
                {% else %}
                {% endif %}
              </div>
                <div class="timeline-detail">

                    <div class="d-flex justify-content-end"><p>{{trip.duration}}</p></div>
                    <div class="row">
                        <div class="col-3 d-flex align-items-end flex-column justify-content-around p-3">
                            <p><strong>{{trip.startTime|date('H:i')}}</strong></p>
                            <p class="d-flex justify-content-center font-control">{{trip.distance}} </p>
                            {% set hour = trip.duration|replace({'heure':'hour'})%}
                            <p class="pt-3"><strong>{{ trip.startTime|date_modify("+" ~ hour)|date('H:i') }}</strong></p>
                        </div>
                        <div class="col-9">
                            <div class="line-detail">
                                <div class="line-content">
                                    <div class="content">
                                        <h1>{{trip.departure}}</h1>
                                    </div>
                                    <div class="content">
                                        <h1> {{trip.arrival}}</h1>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-detail-profile">
                            <div class="col d-flex  justify-content-center">
                                {% if checkBooking != "my" %}
                                    {% if checkBooking == null %}
                                        {% if trip.tripFull == true %}
                                            <p class="contact-button-cancel"><i class="fas fa-users-slash"></i> Trajet Complet !</p>
                                        {% else %}
                                            <a href="{{ path ('booking_new', {'id': trip.id})}}" type="submit" class="contact-button"><i class="fas fa-user-check"></i> Réserver ce trajet</a>
                                        {% endif %}
                                    {% else %}
                                        {% if trip.tripStarted == true and trip.tripCompleted == false %}
                                            <p class="contact-button"><i class="fas fa-car-side"></i> Trajet en cours</p>
                                        {% elseif trip.tripStarted == true and trip.tripCompleted == true %}
                                            <a class="contact-button"><i class="fas fa-check"></i> Trajet terminé</a>
                                        {% else %}
                                            <a href="{{ path ('booking_new', {'id': trip.id})}}" type="submit" class="contact-button-cancel"><i class="far fa-times-circle"></i> Annuler ma réservation</a>
                                        {% endif %}
                                    {% endif %}
                                {% endif %}
                            </div>
                        </div>
                        <span class="custom-separator"></span>
                    </div>
                  <div class="row card-detail-profile">
                  <h4 class="text-center">Informations du conducteur </h4>
                    <a href="{{path('user_show', {'id': trip.driver.id})}}">
                    <div class="row">
                      <div class="col">
                        <img class="img-card"src="{{asset('assets/uploads/profilePicture/') ~ trip.driver.profile_picture}}"/>
                      </div>
                        <div class="col d-flex  flex-column justify-content-center">
                          <p class="font-control">{{trip.driver.firstName}}</p>
                          {% if trip.driver.globalRating %}
                              <p class="font-control"><i style="color: gold;" class="fas fa-star"></i>{{trip.driver.globalRating|round(1, 'floor')}}</p>
                          {% else %}
                              <p class="font-control-rating"><i class="fas fa-star"></i> Pas de note</p>
                          {% endif %}
                      </div>
                      <div class="col d-flex justify-content-end align-items-center font-control fas fa-chevron-right"></div>
                    </div>
                    </a>
                      <div class="row d-flex justify-content-center">
                            {% if trip.driver.phone %}
                              <p class="info-detail"><i style="color:green;" class="far fa-check-circle"></i> Numéro de téléphone</p>
                          {% endif %}
                            {% if checkBooking != "my" %}
                                <a href="{{path('message_discussion_details', {'id': trip.driver.id})}}" class="contact-button"><i style="color:#82b6e8;" class="far fa-comments"></i> Contacter {{trip.driver.firstName}}</a>
                            {% endif %}
                      </div>
                      {% if trip.driver.travelPreferences.discussion == null and trip.driver.travelPreferences.music == null and trip.driver.travelPreferences.smoking == null and trip.driver.travelPreferences.animals == null and trip.driver.travelPreferences.healthPass == null %}
                      {% else %}
                        <span class="custom-separator"></span>
                        <div class="row d-flex justify-content-center">
                            {% if trip.driver.travelPreferences.discussion %}
                                <p class="info-detail"><i class="far fa-comments mx-2"></i>  {{trip.driver.travelPreferences.discussion}}</p>
                            {% endif %}
                            {% if trip.driver.travelPreferences.music %}
                                <p class="info-detail"><i class="fas fa-music mx-2"></i>  {{trip.driver.travelPreferences.music}}</p>
                            {% endif %}
                            {% if trip.driver.travelPreferences.smoking %}
                                <p class="info-detail"><i class="fas fa-smoking mx-2"></i>  {{trip.driver.travelPreferences.smoking}}</p>
                            {% endif %}
                            {% if trip.driver.travelPreferences.animals %}
                                <p class="info-detail"><i class="fas fa-paw mx-2"></i>  {{trip.driver.travelPreferences.animals}}</p>
                            {% endif %}
                            {% if trip.driver.travelPreferences.healthPass %}
                                <p class="info-detail"><i class="fas fa-file-medical mx-2"></i>  {{trip.driver.travelPreferences.healthPass}}</p>
                            {% endif %}
                           
                        </div>
                        {% endif %}
                        {% if trip.driver.vehicule.brand == null and trip.driver.vehicule.model == null and trip.driver.vehicule.vehiculePicture == null %}
                        {% else %}
                      <div class="row">
                        <div class="card-detail-vehicule">
                            <div class="col d-flex  flex-column justify-content-center align-items-center">
                                {% if trip.driver.vehicule.brand %}
                                    <p class="font-control">{{trip.driver.vehicule.brand}} - {{trip.driver.vehicule.model}} </p>
                                {% endif %}
                            </div>
                            <div class="col d-flex  justify-content-end align-items-center">
                                {% if trip.driver.vehicule.vehiculePicture %}
                                    <img class="img-card-vehicule"src="{{asset('assets/uploads/vehiculePicture/') ~ trip.driver.vehicule.vehiculePicture}}"/>
                                {% endif %}
                            </div>
                      </div>
                      {% endif %}
                  </div>
                {% if bookers[0].user is defined %}
                  <span class="custom-separator"></span>
                    <div class="passenger-booker">
                        <h4 class="text-center mt-3 mb-3">Déjà à bord </h4>
                        {% for booker in bookers %}
                        <div class="row card-detail-profile">
                        <a class="d-flex" href="{{path('user_show', {'id':  booker.user.id})}}" >
                                <div class="col d-flex  flex-column justify-content-center">
                                <p class="font-control"> {{ booker.user.firstName}}</p>
                            </div>
                            <div class="col d-flex justify-content-center align-items-center">
                                <img class="img-card-passenger"src="{{asset('assets/uploads/profilePicture/') ~  booker.user.profile_picture}}"/>
                            </div>
                            <div class="col d-flex justify-content-end align-items-center font-control fas fa-chevron-right"></div>
                        </a>
                            </div>
                        
                        {% endfor %}
                    </div>
                {% endif %}
              </div>
          </div>
        </div>
{% endblock %}

templates/trip/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Trip{% endblock %}

{% block body %}
    <h1>Edit Trip</h1>

    {{ include('trip/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('trip_index') }}">back to list</a>

    {{ include('trip/_delete_form.html.twig') }}
{% endblock %}

templates/trip/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Trip index{% endblock %}

{% block body %}
    <h1>Trip index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Departure</th>
                <th>Arrival</th>
                <th>Date_of_trip</th>
                <th>Passengers</th>
                <th>Trip_full</th>
                <th>Trip_completed</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for trip in trips %}
            <tr>
                <td>{{ trip.id }}</td>
                <td>{{ trip.departure }}</td>
                <td>{{ trip.arrival }}</td>
                <td>{{ trip.dateOfTrip ? trip.dateOfTrip|date('Y-m-d') : '' }}</td>
                <td>{{ trip.passengers }}</td>
                <td>{{ trip.tripFull ? 'Yes' : 'No' }}</td>
                <td>{{ trip.tripCompleted ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('trip_show', {'id': trip.id}) }}">show</a>
                    <a href="{{ path('trip_edit', {'id': trip.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('trip_new') }}">Create new</a>
{% endblock %}

templates/trip/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau trajet{% endblock %}

{% block body %}
<div class="container">
<div class="clear-section">
    <h1 class="text-center">Publier un trajet</h1>

    {{ include('trip/_form.html.twig') }}
</div>
</div>

{% endblock %}
{% block javascripts %}
    <script src="{{asset('assets/js/guessPlaces.js')}}"></script>
{% endblock %}

templates/trip/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Trip{% endblock %}

{% block body %}
    <input name="idTripFetch" id="idTripFetch" type="hidden" value="{{ trip.id }}">
       <div class="container">
       <h4 class="text-center">Bravo ! </h4>
            <div class="card-custom">
                <div class="d-flex justify-content-center">
                  <img src="../assets/uploads/custom-pic/custom-car.png" alt="music image" />
                </div>
                <div class="text_content">
                  <h2>{{trip.departure}} -> {{trip.arrival}}</h2>
                  <p class=" text-center">
                    Votre trajet a bien été créé ! 
                  </p>
                </div>
          
                <div class="plan">
                  <div id="card-travel"></div>
                </div>
                <a class="PTP" href="{{path ('user_edit', {'id': app.user.id})}}"> Retourner sur mon profil</a>
                {{ include('trip/_delete_form.html.twig') }}
             </div>
        </div>
{% endblock %}
{% block javascripts %}
  <script src="{{asset('assets/js/routeRequest.js')}}"></script>
{% endblock %}