src/Entity/TravelPreferences.php
<?php

namespace App\Entity;

use App\Repository\TravelPreferencesRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TravelPreferencesRepository::class)
 */
class TravelPreferences
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $discussion;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $music;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $smoking;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $animals;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $health_pass;
  
    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?string $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getDiscussion(): ?string
    {
        return $this->discussion;
    }

    public function setDiscussion(?string $discussion): self
    {
        $this->discussion = $discussion;

        return $this;
    }

    public function getMusic(): ?string
    {
        return $this->music;
    }

    public function setMusic(?string $music): self
    {
        $this->music = $music;

        return $this;
    }

    public function getSmoking(): ?string
    {
        return $this->smoking;
    }

    public function setSmoking(?string $smoking): self
    {
        $this->smoking = $smoking;

        return $this;
    }

    public function getAnimals(): ?string
    {
        return $this->animals;
    }

    public function setAnimals(?string $animals): self
    {
        $this->animals = $animals;

        return $this;
    }

    public function getHealthPass(): ?string
    {
        return $this->health_pass;
    }

    public function setHealthPass(?string $health_pass): self
    {
        $this->health_pass = $health_pass;

        return $this;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use JsonSerializable;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="Cet email est déjà utilisé.")
 */
class User implements UserInterface, JsonSerializable
{
     /**
     * @var string
     *
     * @ORM\Column(name="id", type="string")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class="Doctrine\Bundle\DoctrineBundle\IdGenerator")
     */
    private $id;

     /**
     * @ORM\Column(type="string", length=180, unique=true, nullable=true) 
     * @Assert\Email(
     *     message = "L'email '{{ value }}' n'est pas valide"
     * )
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $last_name;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_of_birth;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $bio;

    /**
     * @ORM\Column(type="string", length=255, nullable=true, options={"default":"default_profile_picture.jpg"})
     */
    private $profile_picture;

    /**
     * @ORM\Column(type="date", nullable=false)
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $profile_completed;

    /**
     * @ORM\Column(type="integer")
     */
    private $trips_made;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $global_rating;

    /**
     * @ORM\ManyToOne(targetEntity=UserExperienceLevel::class)
     */
    private $user_experience;

    /**
     * @ORM\OneToOne(targetEntity=TravelPreferences::class, cascade={"persist","remove"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $travel_preferences;

    /**
     * @ORM\OneToOne(targetEntity=Vehicule::class, cascade={"persist","remove"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $vehicule;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $resetToken;

    public function getId(): ?string
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): ?self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(?string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(?string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getDateOfBirth(): ?\DateTimeInterface
    {
        return $this->date_of_birth;
    }

    public function setDateOfBirth(?\DateTimeInterface $date_of_birth): self
    {
        $this->date_of_birth = $date_of_birth;

        return $this;
    }

    public function getPhone(): ?int
    {
        return $this->phone;
    }

    public function setPhone(?int $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getBio(): ?string
    {
        return $this->bio;
    }

    public function setBio(?string $bio): self
    {
        $this->bio = $bio;

        return $this;
    }

    public function getProfile_Picture(): ?string
    {
        return $this->profile_picture;
    }

    public function setProfile_Picture(?string $profile_picture): self
    {
        $this->profile_picture = $profile_picture;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getProfileCompleted(): ?bool
    {
        return $this->profile_completed;
    }

    public function setProfileCompleted(bool $profile_completed): self
    {
        $this->profile_completed = $profile_completed;

        return $this;
    }

    public function getTripsMade(): ?int
    {
        return $this->trips_made;
    }

    public function setTripsMade(int $trips_made): self
    {
        $this->trips_made = $trips_made;

        return $this;
    }

    public function getGlobalRating(): ?float
    {
        return $this->global_rating;
    }

    public function setGlobalRating(?float $global_rating): self
    {
        $this->global_rating = $global_rating;

        return $this;
    }

    public function getUserExperience(): ?UserExperienceLevel
    {
        return $this->user_experience;
    }

    public function setUserExperience(?UserExperienceLevel $user_experience): self
    {
        $this->user_experience = $user_experience;

        return $this;
    }

    public function getTravelPreferences(): ?TravelPreferences
    {
        return $this->travel_preferences;
    }

    public function setTravelPreferences(?TravelPreferences $travel_preferences): ?self
    {
        $this->travel_preferences = $travel_preferences;

        return $this;
    }

    public function getVehicule(): ?Vehicule
    {
        return $this->vehicule;
    }

    public function setVehicule(?Vehicule $vehicule): ?self
    {
        $this->vehicule = $vehicule;

        return $this;
    }
    
    public function jsonSerialize() {
        return [
            'id' => $this->getId(),
            'firstName' => $this->getFirstName(),
            'lastName' => $this->getLastName(),
            'profile_picture' => $this->getProfile_Picture(),
        ];
    }

    public function getResetToken(): ?string
    {
        return $this->resetToken;
    }

    public function setResetToken(?string $resetToken): self
    {
        $this->resetToken = $resetToken;

        return $this;
    }

}

src/Entity/UserExperienceLevel.php
<?php

namespace App\Entity;

use App\Repository\UserExperienceLevelRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UserExperienceLevelRepository::class)
 */
class UserExperienceLevel
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $experience_level;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getExperienceLevel(): ?string
    {
        return $this->experience_level;
    }

    public function setExperienceLevel(string $experience_level): self
    {
        $this->experience_level = $experience_level;

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\TravelPreferences;
use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email')
            ->add('first_name')
            ->add('last_name')
            ->add('date_of_birth', DateType::class, [
                'required'   => false,
                'widget' => 'single_text',
            ])
            ->add('phone', TextType::class, array(
                'required' => true, 
                'attr' => [
                    'pattern' => '[0-9]{10}', 
                    'maxlength' => 10,
                ])
             )
            ->add('bio', TextareaType::class, [
                'required' => false,
                'attr' => [
                    'class' => 'form-control'
                ],
            ])
            ->add('profile_picture',FileType::class, [
                'label' => 'profil picture',

                // unmapped means that this field is not associated to any entity property
                'mapped' => false,

                // make it optional so you don't have to re-upload the PDF file
                // every time you edit the Product details
                'required' => false,

                // unmapped fields can't define their validation using annotations
                // in the associated entity, so you can use the PHP constraint classes
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypesMessage' => 'Veuillez sélectionner une photo valide',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/jpg',
                            'image/pgn',
                            'image/gif'
                        ],
                    ])
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

templates/user/_delete_form.html.twig
<form class="d-flex flex-column" method="post" action="{{ path('user_delete', {'id': user.id}) }}">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button onclick="return prompt('Ecrivez \'Supprimer mon compte\' pour supprimer votre compte:') == 'Supprimer mon compte'" class="tab-custom-test d-flex flex-column justify-content-center align-items-center delete-button-profile"><i class="far fa-trash-alt"></i> Supprimer mon compte</button>
</form>

templates/user/_form-reset.html.twig
 <section>
        <div class="row">
            {{form_start(formReset)}}
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="custom-input-div">
                    <span>{{ form_label(formReset.password, 'Mot de passe actuel') }}</span>
                    {{ form_widget(formReset.password, {'attr': {'class': 'custom-field-form'}}) }}
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="custom-input-div">
                    {{ form_label(formReset.newPassword.first) }}
                    {{ form_widget(formReset.newPassword.first, {'attr': {'class': 'custom-field-form'}}) }}
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="custom-input-div">
                    {{ form_label(formReset.newPassword.second) }}  
                    {{ form_widget(formReset.newPassword.second, {'attr': {'class': 'custom-field-form'}}) }}
                </div>
            </div>    

            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 mb-4 mt-4 d-flex justify-content-start">
                    <button  type='submit' class="col-md-6 button-update-profile">Mettre à jour</button>
                </div>
            </div>  
            {{form_end(formReset)}}
        </div>
</section>

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <h1>User index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Email</th>
                <th>Roles</th>
                <th>Password</th>
                <th>First_name</th>
                <th>Last_name</th>
                <th>Date_of_birth</th>
                <th>Phone</th>
                <th>Adress</th>
                <th>Country</th>
                <th>City</th>
                <th>Bio</th>
                <th>Profile_picture</th>
                <th>Id_card</th>
                <th>Id_card_file</th>
                <th>Created_at</th>
                <th>Profile_completed</th>
                <th>Trips_made</th>
                <th>Global_rating</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
                <td>{{ user.password }}</td>
                <td>{{ user.firstName }}</td>
                <td>{{ user.lastName }}</td>
                <td>{{ user.dateOfBirth ? user.dateOfBirth|date('Y-m-d') : '' }}</td>
                <td>{{ user.phone }}</td>
                <td>{{ user.adress }}</td>
                <td>{{ user.country }}</td>
                <td>{{ user.city }}</td>
                <td>{{ user.bio }}</td>
                <td>{{ user.profile_Picture }}</td>
                <td>{{ user.idCard ? 'Yes' : 'No' }}</td>
                <td>{{ user.id_Card_File }}</td>
                <td>{{ user.createdAt ? user.createdAt|date('Y-m-d') : '' }}</td>
                <td>{{ user.profileCompleted ? 'Yes' : 'No' }}</td>
                <td>{{ user.tripsMade }}</td>
                <td>{{ user.globalRating }}</td>
                <td>
                    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="20">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/user/show.html.twig
{% if user.travelPreferences != null and user.vehicule != null %}
    {% set checkAllPreferences = (user.travelPreferences.discussion != null) and (user.travelPreferences.smoking != null) and (user.travelPreferences.music != null) and (user.travelPreferences.animals != null) and (user.travelPreferences.healthPass != null) %}
    {% set checkAllVehiculeInfos = (user.vehicule.brand != null) and (user.vehicule.color != null) and (user.vehicule.model != null) %}
{% else %}
    {% set checkAllPreferences = null %}
    {% set checkAllVehiculeInfos = null %}

{% endif %} 
{% extends 'base.html.twig' %}

{% block title %}Profil utilisateur{% endblock %}

{% block body %}
    <div class="mx-auto form-info mt-3">
        <div class="container my-4">
            <h4 class="text-center">Profil de {{ user.firstName }} </h4>
        </div>
        <div class="main-info-profile">
            <div class="row">
                <div class="col-xs-12 col-sm-4 col-md-4 d-flex flex-column align-items-center justify-content-center">
                    <p class="">{{ user.firstName }}</p>
                    <p class="experience-profile">{{ user.userExperience ? user.userExperience.experienceLevel : '' }}</p>
                    <p class="experience-profile d-flex flex-column align-items-center justify-content-center">
                        Trajets effectué</p>
                    <p class="experience-profile d-flex flex-column align-items-center justify-content-center">
                        <strong>{{ user.tripsMade }}</strong>
                    </p>
                </div>
                <div class="col-xs-12 col-sm-4 col-md-4"></div>
                <div class="col-xs-12 col-sm-4 col-md-4">
                    {% if user.profile_picture != '' %}
                        <div class="existing-file">
                            <a href="{{ asset ('/assets/uploads/profilePicture/') ~ user.profile_picture }}" target="_blank"><img class="profile-picture-profile" src="{{ asset ('/assets/uploads/profilePicture/') ~ user.profile_picture }}"/></a>
                        </div>
                    {% else %}
                        <div class="existing-file">
                            <a href="{{ asset ('/assets/uploads/profilePicture/default_profile_picture.jpg') }}" target="_blank"><img class="profile-picture-profile" src="{{ asset ('/assets/uploads/profilePicture/default_profile_picture.jpg') }}"/></a>
                        </div>
                        {% endif %}

                </div>
            </div>

                <div class="row justify-content-between">
                    <div class="col-xs-12 col-sm-6 col-md-6">
                        <div class="input-profile-apropos">
                        {% if user.bio != '' %}
                            <p class="text-center">{{user.bio}}</p>
                        {% endif %}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-6">
                        <p class="text-center mt-4 ml-5"><i style="color: gold;"class="fas fa-star"></i>{{user.globalRating ?  user.globalRating|round(1, 'floor') : 'Aucune note pour l\'instant'}}</p>
                    </div>
                </div>
        </div>
        {% if user.firstName != "Compte supprimé"%}            
        <div class="main-info-profile">
            <div class="d-flex justify-content-center">
                <span class="profile-separator"></div>
            </div>

            <label class="accordion-wrapper">
                <input type="checkbox" class="accordion" hidden/>
                <div class="title">
                    <strong>Ses préférences de voyage</strong>
                    <svg viewBox="0 0 256 512" width="12" title="angle-right" class="side-icon" fill="white">
                        <path d="M224.3 273l-136 136c-9.4 9.4-24.6 9.4-33.9 0l-22.6-22.6c-9.4-9.4-9.4-24.6 0-33.9l96.4-96.4-96.4-96.4c-9.4-9.4-9.4-24.6 0-33.9L54.3 103c9.4-9.4 24.6-9.4 33.9 0l136 136c9.5 9.4 9.5 24.6.1 34z"/>
                    </svg>
                    <svg viewBox="0 0 320 512" height="24" title="angle-down" class="down-icon" fill="white">
                        <path d="M143 352.3L7 216.3c-9.4-9.4-9.4-24.6 0-33.9l22.6-22.6c9.4-9.4 24.6-9.4 33.9 0l96.4 96.4 96.4-96.4c9.4-9.4 24.6-9.4 33.9 0l22.6 22.6c9.4 9.4 9.4 24.6 0 33.9l-136 136c-9.2 9.4-24.4 9.4-33.8 0z"/>
                    </svg>
                </div>
                <div class="content py-2">
                    {% if checkAllPreferences == false %}
                        <p>Aucune préférence pour l'instant</p>
                    {% else %}
                        <div class="form-info mx-auto col-xs-12 col-sm-10 col-md-9">
                            {% if user.travelPreferences.discussion != null %}
                                <h6>
                                    Discussion :
                                </h6>
                                <p class="custom-field-form">{{ user.travelPreferences.discussion }}</p>
                            {% endif %}
                            {% if user.travelPreferences.smoking != null %}
                                <h6>
                                    Fumeur :
                                </h6>
                                <p class="custom-field-form">{{ user.travelPreferences.smoking }}</p>
                            {% endif %}
                                {% if user.travelPreferences.music != null %}
                                <h6>
                                    Musique :
                                </h6>
                                <p class="custom-field-form">{{ user.travelPreferences.music }}</p>
                            {% endif %}
                            {% if user.travelPreferences.animals != null %}
                                <h6>
                                    Animaux :
                                </h6>
                                <p class="custom-field-form">{{ user.travelPreferences.animals }}</p>
                                {% endif %}
                            {% if user.travelPreferences.healthPass != null %}
                                <h6>
                                    Pass Sanitaire :
                                </h6>
                                <p class="custom-field-form">{{ user.travelPreferences.healthPass }}</p>
                            {% endif %}
                        </div>
                    {% endif %}
                </div>
            </label>
            <label class="accordion-wrapper">
                <input type="checkbox" class="accordion" hidden/>
                <div class="title">
                    <strong>Son véhicule</strong>
                    <svg viewBox="0 0 256 512" width="12" title="angle-right" class="side-icon" fill="white">
                        <path d="M224.3 273l-136 136c-9.4 9.4-24.6 9.4-33.9 0l-22.6-22.6c-9.4-9.4-9.4-24.6 0-33.9l96.4-96.4-96.4-96.4c-9.4-9.4-9.4-24.6 0-33.9L54.3 103c9.4-9.4 24.6-9.4 33.9 0l136 136c9.5 9.4 9.5 24.6.1 34z"/>
                    </svg>
                    <svg viewBox="0 0 320 512" height="24" title="angle-down" class="down-icon" fill="white">
                        <path d="M143 352.3L7 216.3c-9.4-9.4-9.4-24.6 0-33.9l22.6-22.6c9.4-9.4 24.6-9.4 33.9 0l96.4 96.4 96.4-96.4c9.4-9.4 24.6-9.4 33.9 0l22.6 22.6c9.4 9.4 9.4 24.6 0 33.9l-136 136c-9.2 9.4-24.4 9.4-33.8 0z"/>
                    </svg>
                </div>
                <div class="content py-2">
                    {% if checkAllVehiculeInfos == false %}
                        <p class="p-4">Aucun véhicule renseigné pour l'instant</p>
                    {% else %}
                    <div class="row mx-auto form-info">
                        <div class="col-xs-12 col-sm-6 col-md-6 d-flex flex-column pl-5 justify-content-center">
                            {% if user.vehicule.brand != null %}
                                <p class="vehicule-profile">Marque :
                                    {{ user.vehicule.brand }}</p>
                            {% endif %}
                            {% if user.vehicule.model != null %}
                                <p class="vehicule-profile">Modèle :
                                {{ user.vehicule.model }}</p>
                            {% endif %}
                            {% if user.vehicule.color != null %}
                                <p class="vehicule-profile">Couleur :
                                    {{ user.vehicule.color }}</p>
                            {% endif %}
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6 d-flex justify-content-center">
                            <img class="profile-picture-profile" src="{{ asset ('/assets/uploads/vehiculePicture/' ~ user.vehicule.vehiculePicture ) }}"/>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </label>
            <div class="row justify-content-around mt-4">
                <div class="col-6">
                    <div class="card-profile"> 
                        <a href="{{path('message_discussion_details', {'id': user.id})}}">
                            <div class="card-profile-content justify-content-center">
                                <i class="far fa-envelope"></i>
                                <p>Contacter {{user.firstName}}</p>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-6">
                    <div class="card-profile">
                        <a href="{{ path ('review_show', {'id': user.id})}}">
                            <div class="card-profile-content justify-content-center">
                                <i class="far fa-star"></i>
                                <p>Avis</p>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
         {% endif %}
    </div>
{% endblock %}

templates/user/user-view-profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <h1>User</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
            <tr>
                <th>First_name</th>
                <td>{{ user.firstName }}</td>
            </tr>
            <tr>
                <th>Last_name</th>
                <td>{{ user.lastName }}</td>
            </tr>
            <tr>
                <th>Date_of_birth</th>
                <td>{{ user.dateOfBirth ? user.dateOfBirth|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Phone</th>
                <td>{{ user.phone }}</td>
            </tr>
            <tr>
                <th>Adress</th>
                <td>{{ user.adress }}</td>
            </tr>
            <tr>
                <th>Country</th>
                <td>{{ user.country }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ user.city }}</td>
            </tr>
            <tr>
                <th>Bio</th>
                <td>{{ user.bio }}</td>
            </tr>
            <tr>
                <th>Profile_picture</th>
                <td>{{ user.profile_Picture }}</td>
            </tr>
            <tr>
                <th>Id_card</th>
                <td>{{ user.idCard ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Id_card_file</th>
                <td>{{ user.id_Card_File }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ user.createdAt ? user.createdAt|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Profile_completed</th>
                <td>{{ user.profileCompleted ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Trips_made</th>
                <td>{{ user.tripsMade }}</td>
            </tr>
            <tr>
                <th>Global_rating</th>
                <td>{{ user.globalRating }}</td>
            </tr>
        </tbody>
    </table>
{% endblock %}